### PR TITLE
Switching to appropriate branch. Adding examples back.

### PR DESCRIPTION
**Pull request by dseaton**
@smarnach I have added a few examples from our courses. Along the way, I encountered some issues and will list those here. @antoviaque has the raw notes I prepared.

Note, I created a new "chapter" in the test course called "AP Instructor Demo - Active Table". This is where I have added three new examples.
https://studio.edge.edx.org/course/DavidsonNext/Ann101/3T2014
1. Is it possible to initialize the “reset button” and “randomization on reset” within the xml?
2. Can we add a small amount of space/margin between input cells? Currently, if everything is wrong, cells are difficult to distinguish. Emphasis on small amount - we just want a slight visual cue.
3. Does edX handle precision within numeric problems? Note, in the first example in the test course, 8, 8.0, 8.0000 all work as the correct answer. If edX already handles this type of thing, we should incorporate.
4. Rollover highlighting for each “input cell” or by “row". Helps students realize this table is interactive.
5. See my last two examples. Each extends past the page width. How should we handle this? Is it possible to either provide column widths? Or just auto fit all columns based on the overall width?
6. $height did not work in one of my examples (see p2_MoneyCreation_LC3_HOA1.xml). Any thoughts? I just changed to a hard value of 175.

7.+help box. Happy to just take JM’s current version.
http://dnextinteractives.s3.amazonaws.com/Calculus/taylor_expEtc.html

### CODE REVIEW

**Comment by smarnach** [comment]
@dseaton Thanks for the feedback.  I will work on this during the next sprint starting Monday evening.

**Comment by smarnach** [comment]
@dseaton I'm not quite sure what you mean by point 3.  Do you want a feature to only accept entries that specify the right number of decimal places?  Something like

```
Numerical(answer=8.0, tolerance=2.5,
          min_significant_digits=2, max_significant_digits=3)
```

would accept 8.0, 08.0, 8.00, 8.1, 8.10, 7.85 but would reject 8, 8.123, 8.000, 7.7, 7.923.  (The significant digits inlcude all digits from the first non-zero digit to the last digit specified – hence 08.0 has two significant digits.)

If what I described is indeed what you are looking for, then I can easily implement this – it's just a few lines of code using Python's built-in `Decimal` type.  I just want to make sure that I understood you correctly.

**Comment by smarnach** [comment]
@dseaton I've looked at the examples – they look good to me.

I've taken the liberty to do a few minor clean-ups on the example files, like removing the example solution from the activetable.xml file and adjusting the image file name to what the image is actually called in the repository.  If you agree with my clean-ups, feel free to merge this pull request.  We will probably want to migrate the examples once #3 is merged, but we can first add them as they are.

On a somewhat related note, once we release an ActiveTable version that is used in real courses, we should add a version number to the file names.  That way, it will be possible to later add new problems with a later ActiveTable version without migrating the old files, and without any filename conflicts.

**Comment by dseaton** [comment]
@smarnach Apologies for the delay.

Regarding number 3, your proposal sounds great. 

Note, some instructors will want to make the significant figures exact - i.e, min_significant_digits=2, max_significant_digits=2. So you may want to make sure that your code can handle that case.

Going to merge, then create a new example using the updated code in pull request #3.

**Pull request merged**
