### PR TITLE
Only sample TR height within tbody.

### LINKED ISSUE #4: Cell height changes for wrong responses
@smarnach @antoviaque The cell height changes after a wrong submission to active table. See my new example [p7 for Money Creation in Macro](https://github.com/open-craft/activetable-jsinput/blob/Daniel/Notes_and_Examples/p7_ActTable_MoneyCreation_LC2_HOA2.xml) 

[Studio Link](https://studio.edge.edx.org/container/i4x://DavidsonNext/Ann101/vertical/102bb8a023ce4d8bb0a7e1e4259faddf?action=new)

Here is a screenshot before any submission
image

Here is the screenshot after a blank submission (notice the scroll bar):
image

### PR DESCRIPTION
**Pull request by Kelketek**
Resolves #4 by allowing each row to have its own height setting.

### CODE REVIEW

**Comment by smarnach** [comment]
@Kelketek This seems to work fine.  Do you have any idea _why_ it works?  The original code is setting the row height for all `<tr>`s, so why should we restrict reading the height back to the table body?

It might be better to store the state data somewhere in `setState()` and reuse it in `getState()`, only adding the values entered by the student.  This could make the whole approach a bit more robust.

**Comment by Kelketek** [comment]
@smarnach The reason it works is because the `<tr>` height is set universally based on whatever the first `<tr>` it grabs is (after all, that's what the jquery there is doing, just grabbing the first one). But the first `<tr>` is going to be the header, and the header's size is not set by student input, but by the course author. So if the user enters nothing, all cells just end up resized by the first row's size.

I'm not certain if this was the intended vector for sizing these rows to begin with, but assuming it is, this fix is best because it makes sure only the rows available to the student are considered.

**Comment by smarnach** [comment]
@Kelketek The height of all rows is set by the course author, and it is set to the same value for both the header row and all rows in the body.  There should never be a row with a different height, so I don't quite understand what difference it would make if the header row gets picked.

Looking at the screenshot, I get the impression that the `css()` method returns the _actual_ height of the row, as opposed to the _configured_ height.  Since in this particular example the first row contains some multi-line cells, its actual height is higher than configured.  If this is actually the case, this fix works more by accident, since any other row could contain multi-line cells as well.

**Comment by Kelketek** [comment]
@smarnach Oh. I thought that was intentional, though a little weird. The css() method should return the computed style property, correct. It did seem like an odd way to go about it.

**Comment by smarnach** [comment]
@Kelketek Sorry for the magic.  I should have refactored this to store the state in a JS object, and only add the values entered to the stored state in `getState()`.  This is probably the only way to conserve the correct cell height.

**Comment by Kelketek** [comment]
@smarnach I've updated this to better keep track of all cell heights. But after re-reading your comments, I'm starting to wonder if I really understood the problem. Could you explain to me, precisely, how row-height is supposed to behave, when it can change, and under what circumstances it would change?

Alternatively, if I did understand it correctly and my fix handles that, let me know.

**Comment by smarnach** [comment]
@Kelketek I suspected that this code would be a bit difficult to understand – that's why we had the quick video chat.  The main reason for this is that jsinput tools are a bit of a hack; another reason is that my code is bad.

Since the problem definition is in the Python code (which was one of the original requirements), we can only transfer it to the JS code by passing it in as the initital state – that's the only way the Python code can transfer information to the JS code, and it can do this only once.  From this point forward, when the page gets reloaded, edx-platform won't pass the initial state to the JS code, but the last state instead.  Thus, we need to store the whole problem definition in the state – not only the bits that might change, but everything that's defined in the Python code.  This is a bit obtuse, but the only way to have the problem definition in the Python code.

When I wrote the first version, the problem definition consisted only of the table, i.e. static text fields and input fields.  The Python code only passed a JSON-encoded two-dimensional array to the JS code.  The `setState()` method built the table from this array, and the `getState()` method recovered the array by looking at the HTML table.  I considered storing the original problem separately from the DOM in a JS object since it wouldn't change, and only adding the values the student entered to the state in the `getState()` method.  However, it turned out that the code became more involved when trying to merge that stored state with the entered values, and it was simpler to recover the whole table from the DOM, so I took this approach.

Unfortunately, I stuck with this approach when I added the further fields to the problem definition – the help text, the row height and the columns widths.  Those values can't ever change.  They only need to be stored in the state to be available for further page loads, not only for the first one.  So for these values, there really is no reason to recover them from the DOM.  They should simply be stored in JS variables and taken from there in the `getState()` method, since they can't change.  That's what I tried to communicate in my previous comments.

I apologize again for the code.

**Comment by Kelketek** [comment]
@smarnach Seems to working! :) Give it a try.

**Comment by smarnach** [comment]
@Kelketek Looks good now. :)  This still contains the change to allow setting individual heights for each row.  I'm not sure whether this feature is needed, but it doesn't seem to hurt, so let's just keep it.

You can remove the [style sheet that was used to set the cell height](https://github.com/open-craft/activetable-jsinput/blob/master/activetable.html#L7) from the HTML template.  Otherwise, :+1:.

**Comment by antoviaque** [comment]
@dseaton FYI, in case you haven't followed, this is merged - you mentioned in #4 that it was resolved for you, but this brings additional fixes which you might want to test. Let me know if you find anything wrong.

**Pull request merged**
